-- Database Schema for Automated AI & Software News SaaS
-- Compatible with PostgreSQL (Supabase / Neon)

-- Enable UUID extension for unique identifiers
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Articles Table
-- Stores the fetched and summarized news items
CREATE TABLE IF NOT EXISTS articles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    url TEXT NOT NULL UNIQUE,
    source TEXT NOT NULL, -- e.g., 'Arxiv', 'HackerNews', 'TechCrunch RSS'
    
    -- Content fields
    summary TEXT, -- Generated by AI (approx 100 words)
    original_snippet TEXT, -- Valid for storing the raw abstract/intro if needed
    
    -- Categorization
    -- We use text check constraints instead of ENUMs for easier future expansion without migration headaches
    category TEXT NOT NULL CHECK (category IN ('AI', 'Computer Science', 'Software Engineering', 'Research')),
    tags TEXT[], -- Array of tags/keywords
    
    -- Metadata
    viability_score INTEGER DEFAULT 0, -- Score indicating relevance or quality (0-100)
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- AI Processing Status
    is_processed BOOLEAN DEFAULT FALSE
);

-- Indexes for frequent query performance
CREATE INDEX IF NOT EXISTS idx_articles_category ON articles(category);
CREATE INDEX IF NOT EXISTS idx_articles_published_at ON articles(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_url ON articles(url);

-- 2. Ingestion Logs
-- Tracks the execution of the daily cron job
CREATE TABLE IF NOT EXISTS ingestion_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    run_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT NOT NULL CHECK (status IN ('SUCCESS', 'FAILURE', 'PARTIAL')),
    articles_added INTEGER DEFAULT 0,
    errors TEXT, -- detailed error message if any
    metadata JSONB -- store extra info like sources checked count
);

-- 3. Views (Optional but helpful for Trending)
-- Example: Trending articles (most recent for now, can be sophisticated later)
CREATE OR REPLACE VIEW trending_articles AS
SELECT *
FROM articles
WHERE published_at >= NOW() - INTERVAL '3 days'
ORDER BY published_at DESC
LIMIT 20;

-- Comments for documentation
COMMENT ON TABLE articles IS 'Main storage for curated news articles';
COMMENT ON COLUMN articles.summary IS 'AI-generated summary of the content';
COMMENT ON TABLE ingestion_logs IS 'Audit log for the daily data fetching pipeline';
